### PR TITLE
fix: now compiles in 426 4.27

### PR DESCRIPTION
**Pull request by WilledgeR**
Hi,

This fixes made the plugin compilable in 4.26 and 4.27

### CODE REVIEW

**Comment by RyroNZ** [comment]
Nice, thanks :)

**Comment by WilledgeR** [comment]
It's compilable but it sill can't `/register_server` correctly.

https://github.com/RyroNZ/UE4MasterServer/blob/e9793fa4b2927bc0abe03ab9b251aa02dacf8efe/Plugin/OnlineSubsystemPython/Source/Private/OnlineSessionInterfacePython.cpp#L276

The actual problem is that `SessionInfo->HostAddr->GetPort()` returns **0** then that **0** travels to MasterServer and would be registered so other clients wont be able to connect.

This issue happens in `UE4.23` and above.

Im looking for the changes that UE community did on Engine/Plugins/Online folder in `4.23` to find a solution.

**Comment by RyroNZ** [comment]
There was something changed in 4.25 afaik, It's possible this is returning HostAddr->SetPort(GetPortFromNetDriver(Subsystem.GetInstanceName())); 0? It might need an override or to read it from the session settings? I don't really support this, it was just quick and dirty for my needs at the time and thought it might be useful. But have at it, if you fix I'm happy to pull it in.

**Comment by WilledgeR** [comment]
I know that you are not working on it anymore, I still appreciate your kindness for publishing the repo.
I learned a lot from your example, You helped the community that was suffering from lack of example for "custom online subsystem"

Here is one of them that used your plugin:
https://github.com/WolfireGames/LowLightCombat2021OSS/blob/main/Plugins/OnlineSubsystemPython/Source/Private/OnlineSessionInterfacePython.cpp

I used his solution to get rid of **"0 port problem"** As you have mentioned `GetPortFromNetDriver` was 0
I created new pull request.

Have a nice day;

**Pull request merged**
